stages:
  train:
    cmd: python -m src.eval.run train -t ${train.agent_name} -m ${train.model} 
      -e
    deps:
    - src/eval/run.py
    - src/eval/evaluators/agent_evals/trainer.py
    - data/goldens/${train.agent_name}/train.json
    params:
    - train.agent_name
    - train.model
    - train.rag
    outs:
    - runs/train_runs
    metrics:
    - runs/train_runs/metrics.json
    plots:
    - runs/train_runs/plots/metrics:
        x: step
  eval:
    cmd: python -m src.eval.run eval -t ${eval.agent_name} -m ${eval.model} -e
    deps:
    - src/eval/run.py
    - src/eval/evaluators/agent_evals/evaluator.py
    - data/goldens/${eval.agent_name}/eval.json
    params:
    - eval.agent_name
    - eval.model
    - eval.rag
    outs:
    - runs/eval_runs
    metrics:
    - runs/eval_runs/metrics.json
    plots:
    - runs/eval_runs/plots/metrics:
        x: step
  benchmark:
    cmd: python src/eval/run.py benchmark -t ${benchmark.agent_name} -m 
      ${benchmark.model} -r ${benchmark.rag} -e
    deps:
    - src/eval/run.py
    - src/eval/evaluators/agent_evals/evaluator.py
    - data/goldens/${benchmark.agent_name}/benchmark.json
    params:
    - benchmark.agent_name
    - benchmark.model
    - benchmark.rag
    outs:
    - runs/benchmark_runs
    metrics:
    - runs/benchmark_runs/metrics.json
    plots:
    - runs/benchmark_runs/plots/metrics:
        x: step
  code_benchmark:
    cmd: python src/eval/run.py code-bench -t ${code.agent_name} -m 
      ${code.model} -r ${code.rag} -e
    deps:
    - src/eval/run.py
    params:
    - code.agent_name
    - code.model
    - code.rag
    outs:
    - runs/code_benchmark_runs
    metrics:
    - runs/code_benchmark_runs/metrics.json
    plots:
    - runs/code_benchmark_runs/plots/metrics:
        x: step
