stages:
  train:
    cmd: python src/eval/run.py train -t ${train.agent_name} -m ${train.model} -r ${train.rag}
    deps:
    - src/eval/run.py
    - data/goldens/${agent_name}/train.json
    params:
    - train.agent_name
    - train.model
    - train.rag
    outs:
    - runs/train_runs
  eval:
    cmd: python src/eval/run.py eval -t ${train.agent_name} -m ${train.model} -r ${train.rag}
    deps:
    - src/eval/run.py
    - data/goldens/${agent_name}/eval.json
  params:
    - eval.agent_name
    - eval.model
    - eval.rag
    outs:
    - runs/eval_runs
  benchmark:
    cmd: python src/eval/run.py benchmark -t ${train.agent_name} -m ${train.model} -r ${train.rag}
    deps:
    - src/eval/run.py  
    - data/goldens/${agent_name}/benchmark.json
    params:
    - benchmark.agent_name
    - benchmark.model
    - benchmark.rag
    outs:
    - runs/benchmark_runs
  code_benchmark:
    cmd: python src/eval/run.py code-bench -t ${train.agent_name} -m ${train.model} -r ${train.rag}
    deps:
    - src/eval/run.py
    params:
    - code.agent_name
    - code.model
    - code.rag
    outs:
    - runs/code_benchmark_runs
metrics:
- eval_runs/metrics.json
plots:
- eval_runs/plots/metrics:
    x: step
