train:
  agent_name: single_agent
  model: gemini-2.5-flash
  rag: true
eval:
  agent_name: single_agent
  model: gemini-2.5-flash
  rag: false
benchmark:
  agent_name: single_agent
  model: gemini-2.5-flash
  rag: false
code:
  agent_name: single_agent
  model: gemini-2.5-flash
  rag: false
  dataset: humaneval
  samples: 
    data/samples/humaneval/humaneval_samples_1773079768596-sanitized.jsonl
