train:
  agent_name: read_agent
  model: gemini-2.5-flash
  rag: true
  no_opt: true
eval:
  agent_name: read_agent
  model: gemini-2.5-flash
  rag: true
benchmark:
  agent_name: read_agent
  model: anthropic/claude-sonnet-4-0
  rag: true
code:
  agent_name: read_agent
  model: anthropic/claude-sonnet-4-0
  rag: true
  dataset: mbpp
  samples: data/samples/mbpp/mbpp_samples_1776263334110-sanitized.jsonl
llm:
  model: anthropic/sonnet-4-0
  dataset: mbpp
  samples: data/samples/mbpp/mbpp_samples_1776095093704-sanitized.jsonl
