"""This is the second agent in the RE agent pipeline and analyzes the requirements generated by the collector agent."""

from typing import Optional
from agents import (AgentBase, get_model_from)
from utils.constants import (AgentRunMode, DEFAULT_MODEL_NAME)
import time

from google.adk.agents import Agent
from utils.logger import setup_logging
from prompt_templates import ANALYZER_AGENT_SYSTEM_PROMPT
from requirement.collector import CollectorOutputModel
from .analyzer_models import AnalyzerOutputModel
from agents import (before_agent, after_agent, before_model, after_model, get_agent_config)


class AnalyzerAgent(AgentBase):
  """This class defines the analyzer agent in the RE phase of the SDLC."""

  def __init__(
      self,
      llm_model_name: str,
      system_prompt: Optional[str] = ANALYZER_AGENT_SYSTEM_PROMPT,
      run_mode: Optional[AgentRunMode] = AgentRunMode.MAIN,
      rag: Optional[bool] = True,
  ):
    super().__init__(llm_model_name, system_prompt, run_mode, rag)

  def get_agent(self) -> Agent:
    return Agent(
        name="analyzer_agent",
        model=get_model_from(self._llm_model_name),
        description=(
            "A requirements analyzer agent that analyzes the raw requirements from the collector"
            " agent."
        ),
        instruction=self._system_prompt,
        input_schema=CollectorOutputModel,
        output_schema=AnalyzerOutputModel,
        generate_content_config=get_agent_config(),
        output_key="analyzer_output",
        before_agent_callback=before_agent,
        after_agent_callback=after_agent,
        before_model_callback=before_model,
        after_model_callback=after_model,
    )


# For testing in adk web ui
run_id = str(int(time.time() * 1000))
setup_logging(run_id, "adk")
agent = AnalyzerAgent(DEFAULT_MODEL_NAME)
root_agent = agent.get_agent()
